[2024-11-26 14:18:34,158: INFO: main: welcome to our log]
[2024-11-27 11:54:52,416: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 11:54:52,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 11:54:52,440: INFO: common: created directory at: artifacts]
[2024-11-27 11:54:52,443: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 11:54:52,446: INFO: 1805952150: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 11:55:40,671: INFO: 1805952150: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 12:06:04,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 12:06:04,718: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 12:06:04,721: INFO: common: created directory at: artifacts]
[2024-11-27 12:06:04,724: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 12:07:35,528: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 12:07:35,532: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 12:07:35,535: INFO: common: created directory at: artifacts]
[2024-11-27 12:07:35,538: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 12:07:35,542: INFO: 2619946697: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 12:08:22,132: INFO: 2619946697: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 12:09:06,567: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 12:09:06,571: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 12:09:06,574: INFO: common: created directory at: artifacts]
[2024-11-27 12:09:06,577: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 12:09:06,582: INFO: 2619946697: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 12:09:51,242: INFO: 2619946697: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 13:00:10,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 13:00:10,130: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 13:00:10,133: INFO: common: created directory at: artifacts]
[2024-11-27 13:00:10,136: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 13:02:02,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 13:02:02,071: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 13:02:02,074: INFO: common: created directory at: artifacts]
[2024-11-27 13:02:02,078: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 13:02:02,082: INFO: 2763251713: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 13:02:51,688: INFO: 2763251713: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 13:54:51,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 13:54:51,058: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 13:54:51,062: INFO: common: created directory at: artifacts]
[2024-11-27 13:54:51,067: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 13:54:51,071: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 13:55:42,284: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 14:20:32,762: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-11-27 14:20:32,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 14:20:32,766: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 14:20:32,768: INFO: common: created directory at: artifacts]
[2024-11-27 14:20:32,769: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 14:20:32,770: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 14:21:22,280: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 14:21:24,350: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-11-27 18:33:49,799: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 18:33:49,815: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 18:33:49,817: INFO: common: created directory at: artifacts]
[2024-11-27 18:41:24,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 18:41:24,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 18:41:24,853: INFO: common: created directory at: artifacts]
[2024-11-27 18:58:30,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 18:58:30,994: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 18:58:30,996: INFO: common: created directory at: artifacts]
[2024-11-27 18:58:30,997: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-11-27 18:58:31,754: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-11-27 19:24:12,736: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-11-27 19:24:12,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 19:24:12,741: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 19:24:12,743: INFO: common: created directory at: artifacts]
[2024-11-27 19:24:12,744: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-27 19:24:12,745: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 19:25:19,838: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-27 19:25:22,438: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-11-27 19:25:22,439: INFO: main: *******************]
[2024-11-27 19:25:22,439: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-11-27 19:25:22,442: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-27 19:25:22,445: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-27 19:25:22,447: INFO: common: created directory at: artifacts]
[2024-11-27 19:25:22,449: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-11-27 19:25:23,138: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-11-27 19:25:24,497: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-11-28 10:49:28,516: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-28 10:49:28,542: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-28 10:49:28,546: INFO: common: created directory at: artifacts]
[2024-11-28 10:49:28,549: INFO: common: created directory at: artifacts\training]
[2024-11-28 10:52:14,300: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-28 10:52:14,305: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-28 10:52:14,311: INFO: common: created directory at: artifacts]
[2024-11-28 10:52:14,315: INFO: common: created directory at: artifacts\training]
[2024-11-28 10:57:32,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-28 10:57:32,119: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-28 10:57:32,124: INFO: common: created directory at: artifacts]
[2024-11-28 10:57:32,127: INFO: common: created directory at: artifacts\training]
[2024-11-28 11:25:03,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-28 11:25:03,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-28 11:25:03,319: INFO: common: created directory at: artifacts]
[2024-11-28 11:25:03,324: INFO: common: created directory at: artifacts\training]
[2024-11-29 18:08:43,399: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-11-29 18:08:43,412: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-29 18:08:43,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-29 18:08:43,424: INFO: common: created directory at: artifacts]
[2024-11-29 18:08:43,424: INFO: common: created directory at: artifacts/data_ingestion]
[2024-11-29 18:08:43,425: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-29 18:14:35,293: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-11-29 18:14:37,891: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-11-29 18:14:37,893: INFO: main: *******************]
[2024-11-29 18:14:37,893: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-11-29 18:14:37,907: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-29 18:14:37,920: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-29 18:14:37,921: INFO: common: created directory at: artifacts]
[2024-11-29 18:14:37,924: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-11-29 18:14:38,944: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-11-29 18:14:39,456: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-11-29 18:14:39,458: INFO: main: *******************]
[2024-11-29 18:14:39,458: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-11-29 18:14:39,462: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-29 18:14:39,464: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-29 18:14:39,465: INFO: common: created directory at: artifacts]
[2024-11-29 18:14:39,467: INFO: common: created directory at: artifacts\training]
[2024-11-29 18:16:41,328: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-11-30 19:19:34,846: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-30 19:19:34,865: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-30 19:19:34,867: INFO: common: created directory at: artifacts]
[2024-11-30 19:21:01,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-30 19:21:01,704: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-30 19:21:01,706: INFO: common: created directory at: artifacts]
[2024-11-30 19:21:33,680: INFO: common: json file saved at: scores.json]
[2024-11-30 19:22:26,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-11-30 19:22:26,917: INFO: common: yaml file: params.yaml loaded successfully]
[2024-11-30 19:22:26,919: INFO: common: created directory at: artifacts]
[2024-11-30 19:22:57,164: INFO: common: json file saved at: scores.json]
[2024-11-30 19:22:59,165: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-11-30 19:22:59,903: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpfm37fanu\model\data\model\assets]
[2024-12-01 09:56:48,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 09:56:48,404: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 09:56:48,408: INFO: common: created directory at: artifacts]
[2024-12-01 09:57:24,903: INFO: common: json file saved at: scores.json]
[2024-12-01 09:57:26,876: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-01 09:57:27,678: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmppkxu_zpq\model\data\model\assets]
[2024-12-01 10:01:27,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 10:01:27,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 10:01:27,293: INFO: common: created directory at: artifacts]
[2024-12-01 10:02:03,413: INFO: common: json file saved at: scores.json]
[2024-12-01 10:02:05,310: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-01 10:02:06,133: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpiso0ab7v\model\data\model\assets]
[2024-12-01 10:25:24,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 10:25:24,710: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 10:25:24,713: INFO: common: created directory at: artifacts]
[2024-12-01 10:26:00,460: INFO: common: json file saved at: scores.json]
[2024-12-01 10:26:02,408: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-01 10:26:03,205: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpbqxi07t3\model\data\model\assets]
[2024-12-01 10:56:59,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 10:56:59,361: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 10:56:59,364: INFO: common: created directory at: artifacts]
[2024-12-01 10:57:35,482: INFO: common: json file saved at: scores.json]
[2024-12-01 10:57:37,346: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-01 10:57:38,147: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmp2xh0asfo\model\data\model\assets]
[2024-12-01 11:10:38,734: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 11:10:38,739: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 11:10:38,742: INFO: common: created directory at: artifacts]
[2024-12-01 11:11:15,075: INFO: common: json file saved at: scores.json]
[2024-12-01 11:30:33,550: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 11:30:33,558: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 11:30:33,562: INFO: common: created directory at: artifacts]
[2024-12-01 11:31:10,305: INFO: common: json file saved at: scores.json]
[2024-12-01 11:31:17,274: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-01 11:31:18,316: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpwo3a761b\model\data\model\assets]
[2024-12-01 12:25:53,831: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 12:25:53,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 12:25:53,836: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 12:25:53,837: INFO: common: created directory at: artifacts]
[2024-12-01 12:25:53,838: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 12:25:53,838: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 12:25:53,865: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA2193D410>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))]
Traceback (most recent call last):
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001AA2193D410>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA2193D410>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 15, in <module>
    data_ingestion.main()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA2193D410>: Failed to resolve 'drive.google.com' ([Errno 11001] getaddrinfo failed)"))
[2024-12-01 14:09:10,041: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 14:09:10,057: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:09:10,069: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:09:10,071: INFO: common: created directory at: artifacts]
[2024-12-01 14:09:10,073: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 14:09:10,075: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:09:55,669: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:09:57,937: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 14:09:57,937: INFO: main: *******************]
[2024-12-01 14:09:57,939: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 14:09:57,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:09:57,945: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:09:57,947: INFO: common: created directory at: artifacts]
[2024-12-01 14:09:57,948: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 14:09:58,736: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 14:09:59,219: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 14:09:59,220: INFO: main: *******************]
[2024-12-01 14:09:59,220: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 14:09:59,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:09:59,227: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:09:59,229: INFO: common: created directory at: artifacts]
[2024-12-01 14:09:59,230: INFO: common: created directory at: artifacts\training]
[2024-12-01 14:11:50,741: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 14:11:50,742: INFO: main: *******************]
[2024-12-01 14:11:50,742: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 14:11:50,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:11:50,749: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:11:50,750: INFO: common: created directory at: artifacts]
[2024-12-01 14:12:23,831: INFO: common: json file saved at: scores.json]
[2024-12-01 14:12:23,832: INFO: common: json file saved at: scores.json]
[2024-12-01 14:12:23,833: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-01 14:14:59,133: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 14:14:59,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:14:59,147: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:14:59,148: INFO: common: created directory at: artifacts]
[2024-12-01 14:14:59,149: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 14:14:59,150: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:15:45,496: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:15:47,715: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 14:15:47,716: INFO: main: *******************]
[2024-12-01 14:15:47,716: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 14:15:47,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:15:47,722: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:15:47,723: INFO: common: created directory at: artifacts]
[2024-12-01 14:15:47,724: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 14:15:48,434: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 14:15:48,860: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 14:15:48,860: INFO: main: *******************]
[2024-12-01 14:15:48,861: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 14:15:48,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:15:48,867: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:15:48,868: INFO: common: created directory at: artifacts]
[2024-12-01 14:15:48,871: INFO: common: created directory at: artifacts\training]
[2024-12-01 14:19:24,947: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 14:19:24,948: INFO: main: *******************]
[2024-12-01 14:19:24,949: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 14:19:24,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:19:24,959: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:19:24,961: INFO: common: created directory at: artifacts]
[2024-12-01 14:19:57,890: INFO: common: json file saved at: scores.json]
[2024-12-01 14:19:57,892: INFO: common: json file saved at: scores.json]
[2024-12-01 14:19:57,893: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-01 14:21:45,678: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 14:21:45,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:21:45,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:21:45,697: INFO: common: created directory at: artifacts]
[2024-12-01 14:21:45,698: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 14:21:45,699: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:22:32,758: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:22:34,808: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 14:22:34,808: INFO: main: *******************]
[2024-12-01 14:22:34,809: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 14:22:34,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:22:34,813: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:22:34,815: INFO: common: created directory at: artifacts]
[2024-12-01 14:22:34,817: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 14:22:35,529: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 14:22:35,934: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 14:22:35,936: INFO: main: *******************]
[2024-12-01 14:22:35,936: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 14:22:35,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:22:35,942: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:22:35,943: INFO: common: created directory at: artifacts]
[2024-12-01 14:22:35,944: INFO: common: created directory at: artifacts\training]
[2024-12-01 14:31:29,605: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 14:31:29,605: INFO: main: *******************]
[2024-12-01 14:31:29,605: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 14:31:29,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:31:29,610: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:31:29,611: INFO: common: created directory at: artifacts]
[2024-12-01 14:32:02,285: INFO: common: json file saved at: scores.json]
[2024-12-01 14:32:02,286: INFO: common: json file saved at: scores.json]
[2024-12-01 14:32:02,286: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-01 14:32:46,232: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 14:32:46,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:32:46,249: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:32:46,251: INFO: common: created directory at: artifacts]
[2024-12-01 14:32:46,252: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 14:32:46,252: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:33:38,104: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 14:33:40,239: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 14:33:40,240: INFO: main: *******************]
[2024-12-01 14:33:40,240: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 14:33:40,244: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:33:40,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:33:40,250: INFO: common: created directory at: artifacts]
[2024-12-01 14:33:40,251: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 14:33:40,873: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 14:33:41,319: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 14:33:41,319: INFO: main: *******************]
[2024-12-01 14:33:41,320: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 14:33:41,323: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:33:41,325: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:33:41,326: INFO: common: created directory at: artifacts]
[2024-12-01 14:33:41,327: INFO: common: created directory at: artifacts\training]
[2024-12-01 14:59:11,498: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 14:59:11,499: INFO: main: *******************]
[2024-12-01 14:59:11,499: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 14:59:11,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 14:59:11,505: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 14:59:11,507: INFO: common: created directory at: artifacts]
[2024-12-01 14:59:44,471: INFO: common: json file saved at: scores.json]
[2024-12-01 14:59:44,472: INFO: common: json file saved at: scores.json]
[2024-12-01 14:59:44,472: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-01 18:11:44,346: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 18:11:44,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 18:11:44,352: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 18:11:44,353: INFO: common: created directory at: artifacts]
[2024-12-01 18:11:44,355: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 18:11:44,356: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 18:16:53,604: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 18:16:55,648: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 18:16:55,648: INFO: main: *******************]
[2024-12-01 18:16:55,649: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 18:16:55,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 18:16:55,653: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 18:16:55,654: INFO: common: created directory at: artifacts]
[2024-12-01 18:16:55,655: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 18:16:56,359: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 18:16:56,699: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 18:16:56,700: INFO: main: *******************]
[2024-12-01 18:16:56,700: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 18:16:56,703: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 18:16:56,705: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 18:16:56,706: INFO: common: created directory at: artifacts]
[2024-12-01 18:16:56,706: INFO: common: created directory at: artifacts\training]
[2024-12-01 18:36:07,056: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 18:36:07,056: INFO: main: *******************]
[2024-12-01 18:36:07,056: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 18:36:07,060: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 18:36:07,062: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 18:36:07,063: INFO: common: created directory at: artifacts]
[2024-12-01 18:36:39,531: INFO: common: json file saved at: scores.json]
[2024-12-01 18:36:39,532: INFO: common: json file saved at: scores.json]
[2024-12-01 18:36:39,532: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-01 18:56:05,414: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 18:56:05,417: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 18:56:05,433: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 18:56:05,434: INFO: common: created directory at: artifacts]
[2024-12-01 18:56:05,435: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 18:56:05,438: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 19:07:56,136: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-01 19:07:56,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 19:07:56,144: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 19:07:56,145: INFO: common: created directory at: artifacts]
[2024-12-01 19:07:56,146: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-01 19:07:56,147: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 19:13:02,121: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-01 19:13:04,208: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-01 19:13:04,209: INFO: main: *******************]
[2024-12-01 19:13:04,210: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-01 19:13:04,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 19:13:04,215: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 19:13:04,216: INFO: common: created directory at: artifacts]
[2024-12-01 19:13:04,218: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-01 19:13:05,151: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-01 19:13:05,569: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-01 19:13:05,570: INFO: main: *******************]
[2024-12-01 19:13:05,570: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-01 19:13:05,573: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 19:13:05,575: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 19:13:05,576: INFO: common: created directory at: artifacts]
[2024-12-01 19:13:05,579: INFO: common: created directory at: artifacts\training]
[2024-12-01 19:34:27,160: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-01 19:34:27,160: INFO: main: *******************]
[2024-12-01 19:34:27,161: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-01 19:34:27,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-01 19:34:27,166: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-01 19:34:27,167: INFO: common: created directory at: artifacts]
[2024-12-01 19:34:59,466: INFO: common: json file saved at: scores.json]
[2024-12-01 19:34:59,469: INFO: common: json file saved at: scores.json]
[2024-12-01 19:34:59,469: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 09:27:14,870: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 09:27:14,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 09:27:14,900: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 09:27:14,901: INFO: common: created directory at: artifacts]
[2024-12-02 09:27:14,902: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 09:27:14,903: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 09:28:02,319: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 09:28:05,017: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 09:28:05,018: INFO: main: *******************]
[2024-12-02 09:28:05,018: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 09:28:05,022: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 09:28:05,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 09:28:05,028: INFO: common: created directory at: artifacts]
[2024-12-02 09:28:05,029: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 09:28:06,133: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 09:28:06,642: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 09:28:06,643: INFO: main: *******************]
[2024-12-02 09:28:06,643: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 09:28:06,646: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 09:28:06,650: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 09:28:06,652: INFO: common: created directory at: artifacts]
[2024-12-02 09:28:06,654: INFO: common: created directory at: artifacts\training]
[2024-12-02 09:53:19,519: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 09:53:19,519: INFO: main: *******************]
[2024-12-02 09:53:19,521: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 09:53:19,532: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 09:53:19,543: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 09:53:19,544: INFO: common: created directory at: artifacts]
[2024-12-02 09:53:52,428: INFO: common: json file saved at: scores.json]
[2024-12-02 09:53:52,430: INFO: common: json file saved at: scores.json]
[2024-12-02 09:53:52,431: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 09:59:31,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 09:59:31,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 09:59:31,944: INFO: common: created directory at: artifacts]
[2024-12-02 10:00:06,720: INFO: common: json file saved at: scores.json]
[2024-12-02 10:00:14,195: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-02 10:00:15,344: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpif9_tr5m\model\data\model\assets]
[2024-12-02 10:22:42,457: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 10:22:42,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:22:42,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:22:42,476: INFO: common: created directory at: artifacts]
[2024-12-02 10:22:42,478: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 10:22:42,479: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 10:23:29,678: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 10:23:31,940: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 10:23:31,941: INFO: main: *******************]
[2024-12-02 10:23:31,941: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 10:23:31,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:23:31,948: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:23:31,949: INFO: common: created directory at: artifacts]
[2024-12-02 10:23:31,950: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 10:23:32,681: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 10:23:33,214: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 10:23:33,215: INFO: main: *******************]
[2024-12-02 10:23:33,216: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 10:23:33,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:23:33,221: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:23:33,223: INFO: common: created directory at: artifacts]
[2024-12-02 10:23:33,224: INFO: common: created directory at: artifacts\training]
[2024-12-02 10:25:24,028: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 10:25:24,029: INFO: main: *******************]
[2024-12-02 10:25:24,029: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 10:25:24,032: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:25:24,035: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:25:24,036: INFO: common: created directory at: artifacts]
[2024-12-02 10:25:24,037: ERROR: main: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url']
Traceback (most recent call last):
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 16, in main
    eval_config = config.get_evaluation_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 83, in get_evaluation_config
    eval_config = EvaluationConfig(
                  ^^^^^^^^^^^^^^^^^
TypeError: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url'
[2024-12-02 10:36:27,882: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 10:36:27,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:36:27,889: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:36:27,890: INFO: common: created directory at: artifacts]
[2024-12-02 10:36:27,893: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 10:36:27,893: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 10:37:15,933: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 10:37:17,983: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 10:37:17,983: INFO: main: *******************]
[2024-12-02 10:37:17,984: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 10:37:17,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:37:17,990: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:37:17,991: INFO: common: created directory at: artifacts]
[2024-12-02 10:37:17,991: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 10:37:18,712: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 10:37:19,179: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 10:37:19,180: INFO: main: *******************]
[2024-12-02 10:37:19,180: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 10:37:19,184: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:37:19,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:37:19,188: INFO: common: created directory at: artifacts]
[2024-12-02 10:37:19,190: INFO: common: created directory at: artifacts\training]
[2024-12-02 10:39:09,889: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 10:39:09,891: INFO: main: *******************]
[2024-12-02 10:39:09,891: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 10:39:09,894: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:39:09,898: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:39:09,900: INFO: common: created directory at: artifacts]
[2024-12-02 10:39:09,901: ERROR: main: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url']
Traceback (most recent call last):
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 16, in main
    eval_config = config.get_evaluation_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 83, in get_evaluation_config
    eval_config = EvaluationConfig(
                  ^^^^^^^^^^^^^^^^^
TypeError: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url'
[2024-12-02 10:54:21,016: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:54:21,037: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:54:21,042: INFO: common: created directory at: artifacts]
[2024-12-02 10:55:20,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:55:20,128: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:55:20,131: INFO: common: created directory at: artifacts]
[2024-12-02 10:56:22,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 10:56:22,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 10:56:22,795: INFO: common: created directory at: artifacts]
[2024-12-02 10:56:58,683: INFO: common: json file saved at: scores.json]
[2024-12-02 10:57:06,138: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-02 10:57:07,214: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpd09etg6i\model\data\model\assets]
[2024-12-02 11:01:18,325: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 11:01:18,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:01:18,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:01:18,334: INFO: common: created directory at: artifacts]
[2024-12-02 11:01:18,335: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 11:01:18,336: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:02:04,992: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:02:07,090: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 11:02:07,091: INFO: main: *******************]
[2024-12-02 11:02:07,091: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 11:02:07,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:02:07,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:02:07,100: INFO: common: created directory at: artifacts]
[2024-12-02 11:02:07,101: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 11:02:07,857: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 11:02:08,292: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 11:02:08,293: INFO: main: *******************]
[2024-12-02 11:02:08,294: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 11:02:08,296: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:02:08,300: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:02:08,302: INFO: common: created directory at: artifacts]
[2024-12-02 11:02:08,302: INFO: common: created directory at: artifacts\training]
[2024-12-02 11:03:58,054: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 11:03:58,055: INFO: main: *******************]
[2024-12-02 11:03:58,056: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 11:03:58,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:03:58,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:03:58,063: INFO: common: created directory at: artifacts]
[2024-12-02 11:03:58,063: ERROR: main: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url']
Traceback (most recent call last):
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 16, in main
    eval_config = config.get_evaluation_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 83, in get_evaluation_config
    eval_config = EvaluationConfig(
                  ^^^^^^^^^^^^^^^^^
TypeError: EvaluationConfig.__init__() got an unexpected keyword argument 'mlflow_url'
[2024-12-02 11:10:55,720: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 11:10:55,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:10:55,727: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:10:55,728: INFO: common: created directory at: artifacts]
[2024-12-02 11:10:55,729: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 11:10:55,730: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:11:44,180: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:11:46,324: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 11:11:46,326: INFO: main: *******************]
[2024-12-02 11:11:46,326: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 11:11:46,328: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:11:46,331: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:11:46,332: INFO: common: created directory at: artifacts]
[2024-12-02 11:11:46,333: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 11:11:47,098: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 11:11:47,522: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 11:11:47,523: INFO: main: *******************]
[2024-12-02 11:11:47,523: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 11:11:47,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:11:47,529: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:11:47,531: INFO: common: created directory at: artifacts]
[2024-12-02 11:11:47,532: INFO: common: created directory at: artifacts\training]
[2024-12-02 11:13:35,935: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 11:13:35,936: INFO: main: *******************]
[2024-12-02 11:13:35,936: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 11:13:35,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:13:35,941: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:13:35,942: INFO: common: created directory at: artifacts]
[2024-12-02 11:13:36,346: ERROR: main: module 'pyexpat.model' has no attribute 'evaluate']
Traceback (most recent call last):
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 55, in <module>
    model_evalution.main()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 18, in main
    evaluation.evaluation()
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 48, in evaluation
    self.score = model.evaluate(self.valid_generator)
                 ^^^^^^^^^^^^^^
AttributeError: module 'pyexpat.model' has no attribute 'evaluate'
[2024-12-02 11:23:17,337: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 11:23:17,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:23:17,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:23:17,346: INFO: common: created directory at: artifacts]
[2024-12-02 11:23:17,347: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 11:23:17,348: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:24:02,849: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:24:04,941: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 11:24:04,942: INFO: main: *******************]
[2024-12-02 11:24:04,943: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 11:24:04,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:24:04,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:24:04,952: INFO: common: created directory at: artifacts]
[2024-12-02 11:24:04,953: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 11:24:05,651: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 11:24:06,027: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 11:24:06,028: INFO: main: *******************]
[2024-12-02 11:24:06,029: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 11:24:06,032: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:24:06,035: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:24:06,037: INFO: common: created directory at: artifacts]
[2024-12-02 11:24:06,038: INFO: common: created directory at: artifacts\training]
[2024-12-02 11:25:55,369: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 11:25:55,370: INFO: main: *******************]
[2024-12-02 11:25:55,370: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 11:25:55,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:25:55,376: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:25:55,376: INFO: common: created directory at: artifacts]
[2024-12-02 11:26:27,855: INFO: common: json file saved at: scores.json]
[2024-12-02 11:26:27,857: INFO: common: json file saved at: scores.json]
[2024-12-02 11:26:27,857: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 11:52:36,506: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 11:52:36,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:52:36,514: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:52:36,515: INFO: common: created directory at: artifacts]
[2024-12-02 11:52:36,516: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 11:52:36,518: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:53:26,140: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 11:53:28,200: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 11:53:28,201: INFO: main: *******************]
[2024-12-02 11:53:28,201: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 11:53:28,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:53:28,208: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:53:28,208: INFO: common: created directory at: artifacts]
[2024-12-02 11:53:28,209: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 11:53:28,954: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 11:53:29,360: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 11:53:29,361: INFO: main: *******************]
[2024-12-02 11:53:29,362: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 11:53:29,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:53:29,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:53:29,368: INFO: common: created directory at: artifacts]
[2024-12-02 11:53:29,369: INFO: common: created directory at: artifacts\training]
[2024-12-02 11:55:18,273: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 11:55:18,274: INFO: main: *******************]
[2024-12-02 11:55:18,274: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 11:55:18,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:55:18,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:55:18,279: INFO: common: created directory at: artifacts]
[2024-12-02 11:55:50,984: INFO: common: json file saved at: scores.json]
[2024-12-02 11:55:50,985: INFO: common: json file saved at: scores.json]
[2024-12-02 11:55:50,985: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 11:58:41,103: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 11:58:41,112: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 11:58:41,117: INFO: common: created directory at: artifacts]
[2024-12-02 11:59:16,048: INFO: common: json file saved at: scores.json]
[2024-12-02 11:59:22,252: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-02 11:59:23,395: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpol0mva2f\model\data\model\assets]
[2024-12-02 12:08:00,721: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 12:08:00,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:08:00,737: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:08:00,740: INFO: common: created directory at: artifacts]
[2024-12-02 12:08:00,741: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 12:08:00,742: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:08:48,767: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:08:50,947: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 12:08:50,948: INFO: main: *******************]
[2024-12-02 12:08:50,948: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 12:08:50,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:08:50,954: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:08:50,955: INFO: common: created directory at: artifacts]
[2024-12-02 12:08:50,956: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 12:08:51,718: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 12:08:52,159: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 12:08:52,160: INFO: main: *******************]
[2024-12-02 12:08:52,160: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 12:08:52,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:08:52,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:08:52,170: INFO: common: created directory at: artifacts]
[2024-12-02 12:08:52,171: INFO: common: created directory at: artifacts\training]
[2024-12-02 12:10:42,355: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 12:10:42,355: INFO: main: *******************]
[2024-12-02 12:10:42,356: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 12:10:42,359: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:10:42,361: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:10:42,361: INFO: common: created directory at: artifacts]
[2024-12-02 12:11:15,418: INFO: common: json file saved at: scores.json]
[2024-12-02 12:11:15,419: INFO: common: json file saved at: scores.json]
[2024-12-02 12:11:15,419: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 12:17:27,599: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 12:17:27,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:17:27,606: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:17:27,607: INFO: common: created directory at: artifacts]
[2024-12-02 12:17:27,609: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 12:17:27,610: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:18:19,721: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:18:21,834: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 12:18:21,835: INFO: main: *******************]
[2024-12-02 12:18:21,835: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 12:18:21,838: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:18:21,841: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:18:21,842: INFO: common: created directory at: artifacts]
[2024-12-02 12:18:21,844: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 12:18:22,580: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 12:18:23,021: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 12:18:23,021: INFO: main: *******************]
[2024-12-02 12:18:23,022: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 12:18:23,026: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:18:23,029: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:18:23,029: INFO: common: created directory at: artifacts]
[2024-12-02 12:18:23,031: INFO: common: created directory at: artifacts\training]
[2024-12-02 12:20:17,990: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 12:20:17,990: INFO: main: *******************]
[2024-12-02 12:20:17,991: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 12:20:17,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:20:17,998: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:20:17,999: INFO: common: created directory at: artifacts]
[2024-12-02 12:20:55,570: INFO: common: json file saved at: scores.json]
[2024-12-02 12:20:55,571: INFO: common: json file saved at: scores.json]
[2024-12-02 12:20:55,572: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 12:38:00,181: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 12:38:00,185: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:38:00,187: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:38:00,187: INFO: common: created directory at: artifacts]
[2024-12-02 12:38:00,188: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 12:38:00,189: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:38:43,742: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:38:45,119: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 12:38:45,119: INFO: main: *******************]
[2024-12-02 12:38:45,120: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 12:38:45,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:38:45,123: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:38:45,124: INFO: common: created directory at: artifacts]
[2024-12-02 12:38:45,125: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 12:38:45,658: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 12:38:45,985: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 12:38:45,986: INFO: main: *******************]
[2024-12-02 12:38:45,986: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 12:38:45,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:38:45,989: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:38:45,990: INFO: common: created directory at: artifacts]
[2024-12-02 12:38:45,991: INFO: common: created directory at: artifacts\training]
[2024-12-02 12:40:20,035: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-02 12:40:20,036: INFO: main: *******************]
[2024-12-02 12:40:20,036: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-02 12:40:20,038: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:40:20,040: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:40:20,041: INFO: common: created directory at: artifacts]
[2024-12-02 12:40:48,999: INFO: common: json file saved at: scores.json]
[2024-12-02 12:40:49,000: INFO: common: json file saved at: scores.json]
[2024-12-02 12:40:53,548: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-02 12:40:54,139: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpopf2xxh6\model\data\model\assets]
[2024-12-02 12:41:54,630: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-02 12:43:38,634: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-02 12:43:38,636: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:43:38,647: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:43:38,648: INFO: common: created directory at: artifacts]
[2024-12-02 12:43:38,648: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-02 12:43:38,649: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:44:21,836: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-02 12:44:23,100: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-02 12:44:23,101: INFO: main: *******************]
[2024-12-02 12:44:23,102: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-02 12:44:23,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:44:23,107: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:44:23,107: INFO: common: created directory at: artifacts]
[2024-12-02 12:44:23,108: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-02 12:44:23,541: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-02 12:44:23,842: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-02 12:44:23,843: INFO: main: *******************]
[2024-12-02 12:44:23,844: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-02 12:44:23,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-02 12:44:23,847: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-02 12:44:23,848: INFO: common: created directory at: artifacts]
[2024-12-02 12:44:23,850: INFO: common: created directory at: artifacts\training]
[2024-12-03 09:27:24,858: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-03 09:27:24,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 09:27:24,888: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 09:27:24,889: INFO: common: created directory at: artifacts]
[2024-12-03 09:27:24,890: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-03 09:27:24,891: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-03 09:28:08,301: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-03 09:28:09,786: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-03 09:28:09,787: INFO: main: *******************]
[2024-12-03 09:28:09,787: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-03 09:28:09,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 09:28:09,794: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 09:28:09,795: INFO: common: created directory at: artifacts]
[2024-12-03 09:28:09,796: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-03 09:28:10,457: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-03 09:28:10,783: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-03 09:28:10,784: INFO: main: *******************]
[2024-12-03 09:28:10,784: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-03 09:28:10,787: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 09:28:10,789: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 09:28:10,789: INFO: common: created directory at: artifacts]
[2024-12-03 09:28:10,790: INFO: common: created directory at: artifacts\training]
[2024-12-03 09:46:00,579: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-03 09:46:00,580: INFO: main: *******************]
[2024-12-03 09:46:00,580: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-03 09:46:00,593: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 09:46:00,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 09:46:00,605: INFO: common: created directory at: artifacts]
[2024-12-03 09:46:33,049: INFO: common: json file saved at: scores.json]
[2024-12-03 09:46:33,050: INFO: common: json file saved at: scores.json]
[2024-12-03 09:46:38,408: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-03 09:46:39,021: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmp73i1el3y\model\data\model\assets]
[2024-12-03 09:47:37,538: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-03 14:36:18,196: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-03 14:36:18,201: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 14:36:18,204: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 14:36:18,205: INFO: common: created directory at: artifacts]
[2024-12-03 14:36:18,206: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-03 14:36:18,208: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-03 14:37:07,210: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1sIFSQT3dMpiu6Odfdz7z5V9Dtk-UN9mi/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-03 14:37:09,451: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-03 14:37:42,002: INFO: stage_02_prepare_base_model: *******************]
[2024-12-03 14:37:42,004: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-03 14:37:42,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 14:37:42,012: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 14:37:42,014: INFO: common: created directory at: artifacts]
[2024-12-03 14:37:42,015: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-03 14:37:42,905: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-03 14:37:43,272: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-03 14:37:54,672: INFO: stage_03_model_training: *******************]
[2024-12-03 14:37:54,673: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-12-03 14:37:54,677: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 14:37:54,680: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 14:37:54,681: INFO: common: created directory at: artifacts]
[2024-12-03 14:37:54,683: INFO: common: created directory at: artifacts\training]
[2024-12-03 14:55:47,281: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-03 14:56:00,048: INFO: stage_04_model_evaluation: *******************]
[2024-12-03 14:56:00,049: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-03 14:56:00,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-03 14:56:00,056: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-03 14:56:00,058: INFO: common: created directory at: artifacts]
[2024-12-03 14:56:33,217: INFO: common: json file saved at: scores.json]
[2024-12-03 14:56:33,219: INFO: common: json file saved at: scores.json]
[2024-12-03 14:56:42,506: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-12-03 14:56:43,605: INFO: builder_impl: Assets written to: C:\Users\rohit\AppData\Local\Temp\tmpuhua97kf\model\data\model\assets]
[2024-12-03 14:57:52,231: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-03 19:40:55,831: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-03 19:40:55,833: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-03 19:42:57,651: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:42:57] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:43:19,180: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:43:19] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:43:34,806: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:43:34] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:43:42,800: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-03 19:43:42,823: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:43:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-03 19:43:45,285: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-03 19:43:45,295: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:43:45] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-03 19:44:43,752: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:44:43] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:45:14,301: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:45:14] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:49:49,849: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-03 19:49:49,850: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-03 19:50:09,406: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:50:09] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:51:27,245: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-03 19:51:27,248: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-03 19:52:05,953: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:52:05] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:53:39,081: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-03 19:53:39,083: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-03 19:54:16,990: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:54:16] "GET / HTTP/1.1" 200 -]
[2024-12-03 19:54:31,862: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-03 19:54:31,876: INFO: _internal: 127.0.0.1 - - [03/Dec/2024 19:54:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 10:55:37,937: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-04 10:55:37,939: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 10:56:00,079: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 10:56:00] "GET / HTTP/1.1" 200 -]
[2024-12-04 10:56:46,656: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 10:56:46,695: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 10:56:46] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 10:59:02,196: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 10:59:02] "GET / HTTP/1.1" 200 -]
[2024-12-04 10:59:16,909: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 10:59:16,919: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 10:59:16] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 11:29:26,613: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-04 11:29:26,615: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 11:30:05,443: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 11:30:05] "GET / HTTP/1.1" 200 -]
[2024-12-04 11:31:01,500: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 11:31:01,507: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 11:31:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 11:57:42,989: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.4:8080]
[2024-12-04 11:57:42,990: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 11:58:51,068: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 11:58:51] "GET / HTTP/1.1" 200 -]
[2024-12-04 11:59:42,480: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 11:59:42,489: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 11:59:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 12:10:04,812: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 12:10:04] "GET / HTTP/1.1" 200 -]
[2024-12-04 12:10:14,730: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 44, in predictRoute
    def trainRoute():
                 ^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 12:10:14,781: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 12:10:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 18:27:15,222: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-04 18:27:15,224: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 18:27:23,417: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:27:23] "GET / HTTP/1.1" 200 -]
[2024-12-04 18:27:32,236: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 13, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 18:27:32,258: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:27:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 18:39:52,937: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-04 18:39:52,937: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 18:40:02,206: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:40:02] "GET / HTTP/1.1" 200 -]
[2024-12-04 18:40:11,365: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 15, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 18:40:11,402: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:40:11] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 18:49:22,502: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-04 18:49:22,503: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 18:49:28,838: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:49:28] "GET / HTTP/1.1" 200 -]
[2024-12-04 18:49:35,809: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-12-04 18:49:35,825: INFO: _internal: 127.0.0.1 - - [04/Dec/2024 18:49:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-04 19:19:10,668: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-04 19:19:10,670: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-04 19:19:29,901: INFO: _internal: 192.168.1.5 - - [04/Dec/2024 19:19:29] "GET / HTTP/1.1" 200 -]
[2024-12-04 19:19:38,096: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    raise FileNotFoundError(f"Model file not found at {model_path}. Please ensure the model is saved correctly.")
FileNotFoundError: Model file not found at model\model.h5. Please ensure the model is saved correctly.
[2024-12-04 19:19:38,111: INFO: _internal: 192.168.1.5 - - [04/Dec/2024 19:19:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-05 11:33:09,159: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-05 11:33:09,161: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-05 11:33:14,997: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:33:14] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:33:27,990: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohit\anaconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\projects\Kidney-Disease-Classification-Deep-Learning-Project\app.py", line 46, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
                 ^^^^^^^^^^^^^^
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_img'
[2024-12-05 11:33:28,009: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:33:28] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-05 11:40:06,477: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.5:8080]
[2024-12-05 11:40:06,480: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-05 11:40:10,989: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:40:10] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:40:22,747: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:40:22] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 11:40:51,400: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:40:51] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 11:41:57,593: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:41:57] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 11:43:52,519: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:43:52] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 11:47:02,393: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000229C2E0E700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-12-05 11:47:02,402: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:47:02] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 11:56:05,954: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:56:05] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:56:46,963: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:56:46] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:56:48,023: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:56:48] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:56:49,053: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:56:49] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:58:15,372: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:58:15] "GET / HTTP/1.1" 200 -]
[2024-12-05 11:58:50,733: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 11:58:50] "GET / HTTP/1.1" 200 -]
[2024-12-05 12:04:39,414: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 12:04:39] "GET / HTTP/1.1" 200 -]
[2024-12-05 12:05:12,636: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000229C4F56160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-12-05 12:05:12,644: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 12:05:12] "POST /predict HTTP/1.1" 200 -]
[2024-12-05 12:26:13,176: INFO: _internal: 127.0.0.1 - - [05/Dec/2024 12:26:13] "POST /predict HTTP/1.1" 200 -]
